apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic-angular
  description: Pet Clinic main website
  annotations:
    backstage.io/source-location: url:https://bitbucket.org/neoris-global/dso.petclinic-angular/src/master/
    sonarqube.org/project-key: com.neoris.ddc.devsecops.aws:web-angular # YOUR_PROJECT_KEY
    bitbucket.org/repository-slug: 'neoris-global/dso.petclinic-angular' # {workspace_slug}/{repo_slug}
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    prometheus.io/alert: all
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=backstage-stg'
    backstage.io/kubernetes-namespace: 'backstage'
    # backstage.io/kubernetes-id: dso-backstage
    circleci.com/project-slug: bitbucket/backstage-repos/backstage-dex-image
    grafana/overview-dashboard: 'https://grafana.aws.neoris.cloud/d/cluster-costs/cluster-cost-and-utilization-metrics?orgId=1&refresh=15m&viewPanel=116&kiosk=true'
    jenkins.io/job-full-name: 'backstage'
  tags:
    - angular
  links:
    - url: https://petclinic-angular.aws.neoris.cloud/
      title: Web dev
      icon: code
    - url: https://bitbucket.org/neoris-global/dso.petclinic-angular
      title: Bitbucket Repo
      icon: bitbucket
spec:
  type: website
  lifecycle: production
  system: testops
  owner: neoris
  consumesApis: ['api:petclinic-rest']
