name: Builder
on:
  workflow_dispatch:
  push:
    branches:
    - feat/*
  pull_request:
    types: [opened]

env:
  CLUSTER_PROVIDER: ${{ vars.CLUSTER_PROVIDER }}

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install-dependencies
      run: yarn install --frozen-lockfile
    - name: yarn-tsc
      run: yarn tsc
    - name: yarn-builder
      run: yarn build:backend --config ../../app-config.yaml
    - name: build-image
      run: 

