name: BackStage builder
on:
  workflow_dispatch:
  push:
    branches:
      - feat/*
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  AWS_REGION: eu-west-1
  AWS_ECR_REPOSITORY: cicd/backstage

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate environment variables
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "MY_COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          echo "MY_BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME//\//-}}" >> $GITHUB_ENV

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install yarn
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Compile
        run: yarn tsc

      - name: Build backend
        run: yarn build:backend --config ../../app-config.yaml

      - name: Scan Dockerfile with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: ./packages/backend/Dockerfile
          severity: "CRITICAL"
          format: "sarif"
          output: "results-dockerfile.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "results-dockerfile.sarif"
          category: "docker-file"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/backend/Dockerfile
          load: true
          tags: ${{ env.AWS_ECR_REPOSITORY }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.AWS_ECR_REPOSITORY }}
          severity: "CRITICAL"
          format: "sarif"
          output: "results-dockerimage.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "results-dockerimage.sarif"
          category: "docker-image"

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          region: ${{ env.AWS_REGION }}
          local-image: ${{ env.AWS_ECR_REPOSITORY }}
          image: ${{ env.AWS_ECR_REPOSITORY }}:${{ env.MY_BRANCH_NAME }}-${{ env.MY_COMMIT_SHORT_SHA }}
