name: BackStage deploy
on:
  workflow_dispatch:
    inputs:
        image_version:
            description: 'My parameter description'
            required: true

env:
  AWS_REGION: eu-west-1
  AWS_ECR_REPOSITORY: cicd/backstage
  HOST_ECR: 061496817474.dkr.ecr.eu-west-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token-clone
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: DDC-NEORIS/devtools-k8s
          token: ${{ steps.generate-token-clone.outputs.token }} # `GH_PAT` is a secret that contains your PAT
          path: .
      - name: deploy k8s repo
        run: |
          ls -la
          chmod +x ./scripts/backstage-deploy.sh
          ./scripts/backstage-deploy.sh ${{ github.event.inputs.image_version }} ${{ steps.generate-token-clone.outputs.token }} ${{env.HOST_ECR}}

