name: BackStage builder
on:
  workflow_dispatch:
  push:
    branches:
    - feat/*
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  CLUSTER_PROVIDER: ${{ vars.CLUSTER_PROVIDER }}

jobs:
  backstage-builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/cache/restore@v3
      id: restore-cache
      with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}


    - name: install-dependencies
      run: yarn install --frozen-lockfile

    - uses: actions/cache/save@v3
      if: always() // or any other condition to invoke the save action
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
      
    
    - name: yarn-tsc
      run: yarn tsc

    - name: yarn-builder
      run: yarn build:backend --config ../../app-config.yaml

    - name: scan Dockerfile trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: ./packages/backend/Dockerfile
        severity: 'CRITICAL'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Sube Trivy scan resultado a GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: build-image
      uses: int128/kaniko-action@v1
      with:
        context: .
        file: packages/backend/Dockerfile
        tags: 061496817474.dkr.ecr.eu-west-1.amazonaws.com/cicd/backstage:develop-fc976e4-20231009-211554
        kaniko-args: |
          --tar-path
          ${{ env.GITHUB_WORKSPACE }}/image.tar 
          
        push: false
        

    - run: |
        ls -laR
        
    - name: trivy-analisis
      uses: aquasecurity/trivy-action@master
      with:
        input: ${{ env.GITHUB_WORKSPACE }}/image.tar
        severity: 'CRITICAL'
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Sube Trivy scan resultado a GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
      
    