name: Build container release images
on:
  push:
    tags:
      - '*'

permissions:
  actions: read
  contents: read
  packages: write
  security-events: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      push_to_images: |
        ghcr.io/${{ github.repository }}
      flavor: |
        latest=false
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
    secrets: inherit