name: Build alpha container image
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  packages: write
  security-events: write

jobs:
  build-app:
    uses: ./.github/workflows/build-app.yml
    with:
      cache_artifacts: true
    secrets: inherit
  verify-app:
    needs:
      - build-app
    uses: ./.github/workflows/verify-app.yml
    secrets: inherit
  build-image:
    needs:
      - build-app
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      push_to_images: |
        ghcr.io/${{ github.repository }}
      labels: |
        org.opencontainers.image.description=Alpha build image used for development environment
      flavor: |
        latest=auto
      tags: |
        type=raw,value=edge
        type=sha
    secrets: inherit
  deploy-image:
    needs:
      - build-image
    uses: ./.github/workflows/deploy-container-image.yml
    with:
      app_id: backstage
      environment: staging
      image_tag: ${{ needs.build-image.outputs.image_tag }}
      manifest_path: tools/base/backstage/backstage-stg/app/deployment.yaml
      manifest_type: deployment
    secrets: inherit