name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch: # Esto permite ejecutar manualmente el flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello World
        run: echo "Hello, World!"

